name: Java-ci/cd
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: complete
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup java-version
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build
        run: mvn clean package

      - name: SonarQube Analysis
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ vars.PROJECT_NAME }} \
            -Dsonar.organization=${{ vars.ORG_NAME }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=dev \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifacts
          path: complete/target/*.jar

